<?php

return [
    'QUICKPAY_PRIVATE_KEY' => env('QUICKPAY_PRIVATE_KEY'),
    'QUICKPAY_API_KEY' => env('QUICKPAY_API_KEY'),
    'QUICKPAY_MERCHANT_ID' => env('QUICKPAY_MERCHANT_ID'),
    'QUICKPAY_FACILITATOR' => env('QUICKPAY_FACILITATOR'),
    'QUICKPAY_TEST_MODE' => env('QUICKPAY_TEST_MODE'),
    'QUICKPAY_AUTO_CAPTURE' => env('QUICKPAY_AUTO_CAPTURE'),
];